### PR TITLE
Allow selecting month and year separately

### PR DESCRIPTION
**Pull request by agustinrhcp**
This change adds the ability to pick a month or a year. It's not perfect, but I needed something like this for my project so I thought on trying to get it merged here. 
I'm also using custom styles, so happy to hear your thoughts on the styling.

Cheers
Screen Shot 2020-03-18 at 12 22 22 AM
Screen Shot 2020-03-18 at 12 22 56 AM

### CODE REVIEW

**Comment by JDemler** [comment]
Thanks for the contribution. 
Will probably be to review it this weekend.

**Comment by JDemler** [comment]
Hey @agustinrhcp 

I just looked at your changes and there are multiple issues. These could all be resolved, but I am not sure the underlying idea is fitting for this package.

Is there some general design documentation about datepickers that work like you implemented them? What are the tradeoffs?

Maybe you can expand on your motivation to make it easier for me to decide if this idea is worth the trouble.

Cheers,
Jakob

**Comment by agustinrhcp** [comment]
Hey @JDemler 

You are totally right. I follow the ui/ux designs from ant you can check them [here](https://ant.design/components/date-picker).

My motivation doesn't come from copying those style, but mostly having an easy way to pick a date from X years ago, without having to click X * 12 times or having to write it down. 

Happy to hear your thoughts, and I'd love to get some feedback.

Thanks,
Agustin

**Comment by JDemler** [comment]
Thanks for the explanation. For now I will not consider merging this pull request, as it extends this package in a way that is not suitable for all users.

Solving this by adding more configuration is a deep rabbit hole I am currently not willing to dive into.

Cheers,
Jakob

**Comment by agustinrhcp** [comment]
@JDemler No problem, I wasn't expecting this PR to be merged straight away, but I was hoping you'd told me what's that you don't like so I could fix it. 
The change is not expected to break current functionality, just adds in top of it. 

Cheers, Agustin

**Pull request closed without merging**
