### PR TITLE
Fixup className and minor API additions

### PR DESCRIPTION
**Pull request by joecorkerton**
First off, thanks for updating this for 0.19! This package was a blocker for us upgrading.

Two changes here:

1. Prepend classNamespace to container element

Why? 

If you are using bootstrap, container is a special class, hence we should not use it here for no reason.

2. Add open and close methods

Why?

For our use case we need to open and close the datepicker manually as we do not allow the user to interact with the input directly.

Also ran elm-format as part of these changes.

(Can remove this if you prefer)

### CODE REVIEW

**Comment by JDemler** [comment]
Thanks for the PR.

Change two seems plausible and adds to the API. 

The first change seems to actually fix a regression introduced [here](https://github.com/elm-community/elm-datepicker/pull/82). Thanks for catching it :+1: 

Note, that before, the local `class` function was called (not `Hmtl.Attributes.class`), which called `mkClass` which prepended the namespace.

You seem to have a different version of elm-format than me (or it is differently configured). Can you please remove the format changes and tell me which version of elm-format you are using?

**Comment by joecorkerton** [comment]
I'm using the latest version of elm-format, 0.8.0

**Comment by JDemler** [comment]
I was on 0.6...
I'll merge your format changes as well.

**Comment by JDemler** [comment]
Added examples and tests for the new methods and published under [2.1.0](https://package.elm-lang.org/packages/CurrySoftware/elm-datepicker/latest/).

Thanks for the PR!

**Pull request merged**
