### PR TITLE
Added new simple function to return the initial date.

### PR DESCRIPTION
**Pull request by Bernardoow**

### CODE REVIEW

**Comment by JDemler** [comment]
Thank you for your PR.

I am a bit confused as to the reasoning behind this. The way I see it you have three ways to initialize the `DatePicker`:

1. `DatePicker.init` (This sets the inital date to `Date.fromCalendarDate 1992 May 31`)
2. `DatePicker.initFromDate` (You set the inital date yourself)
3. `DatePicker.initFromDates` (You also set the initial date yourself)

In all cases you already know the initial date.

**Comment by Bernardoow** [comment]
Hi @JDemler, good morning (Obs here is 06:46 am)!!

OK. Let me explain... My PR is because in the option 1. DatePicker.init (This sets the inital date to Date.fromCalendarDate 1992 May 31), the date begin with (Date.fromCalendarDate 1992 May 31) but a command is executed to get the current date https://github.com/CurrySoftware/elm-datepicker/blob/23bd4ca7f657fcb4041f8bb5d193ce2926dc90f8/src/DatePicker.elm#L207.

In this moment, the current date is the actual system's date, and I don't know what the date is because it's locked inside datepicker. ( I tried to get hehehe)

On my project I want to disable date before the current date, so I have two options. Execute the same cmd that is executed inside datepicker or get the current date (Model.today).

Please look at my example using my suggestion: https://github.com/Bernardoow/elm-datepicker/blob/6643cfc965865ed01858cfc5bb252d09e2c1f40a/examples/simple-with-validate-date/Simple.elm#L24.

Because this explanation I suggested a function to return the current date.

**Comment by JDemler** [comment]
I understand.

Please extend the documentation of your `initialDate` function to generally describe this scenario.

**Comment by Bernardoow** [comment]
Hi @JDemler,

Done. I improved the doc to the function and changed the name of her.

**Comment by JDemler** [comment]
Thank you for the changes and this PR.

I will try to do a minor release containing this change this week.
Cheers!

**Comment by Bernardoow** [comment]
Hi @JDemler,

Thank you for have accepted my pr.

Cheers!

**Comment by JDemler** [comment]
@Bernardoow I just released version 3.1.0 which includes your change!

Thanks again.

**Pull request merged**
